---
# handlers file for ansible-role-rabbitmq

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped

- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted
